# NumPy Basics: Arrays and Vectorized Computation

In [1]:
import numpy as np

In [3]:
my_arr = np.arange(1_000_000)
%timeit my_arr2 = my_arr * 2

878 μs ± 52 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [4]:
my_list = list(range(1_000_000))
%timeit my_list2 = [x * 2 for x in my_list]

25.9 ms ± 955 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


# The NumPy ndarray: A Multidimensional Array Object

In [5]:
data = np.array([[1.5,-0.1,3],[0,-3,6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [6]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [7]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [8]:
data.shape

(2, 3)

In [9]:
data.dtype

dtype('float64')

## Creating ndarrays

In [11]:
data1 = [6,7.5,8,0,1]
data1

[6, 7.5, 8, 0, 1]

In [12]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [13]:
data2 = [[1,2,3,4],[5,6,7,8]]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [14]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
arr2.ndim

2

In [16]:
arr2.shape

(2, 4)

In [17]:
arr1.dtype

dtype('float64')

In [18]:
arr2.dtype

dtype('int64')

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
#该数组将包含该位置内存中已有的任何值。数组中的值是不可预测的，在使用前应予以覆盖
np.empty((2, 3, 2))

array([[[0.00000000e+000, 1.00937611e-320],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 2.46567317e+179]],

       [[4.96027437e-090, 7.12309074e-067],
        [9.98573284e-048, 4.88960160e-033],
        [3.99910963e+252, 1.46030983e-319]]])

In [24]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Some important NumPy array creation functions

|Function	|Description|
|---|---|
|array	|Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a data type or explicitly specifying a data type; copies the input data by default|
||通过推断数据类型或显式指定数据类型，将输入数据（列表、元组、数组或其他序列类型）转换为 ndarray;默认情况下，复制输入数据|
|asarray	|Convert input to ndarray, but do not copy if the input is already an ndarray|
||将输入转换为 ndarray，但如果输入已经是 ndarray，则不要复制|
|arange	|Like the built-in range but returns an ndarray instead of a list|
||类似于内置范围，但返回 ndarray 而不是列表|
|ones, ones_like	|Produce an array of all 1s with the given shape and data type; ones_like takes another array and produces a ones array of the same shape and data type|
||生成具有给定形状和数据类型的所有 1 的数组;ones_like 接受另一个数组并生成一个相同形状和数据类型的 ones 数组|
|zeros, zeros_like	|Like ones and ones_like but producing arrays of 0s instead|
||像 1 和 ones_like，但生成 0 的数组|
|empty, empty_like	|Create new arrays by allocating new memory, but do not populate with any values like ones and zeros|
||通过分配新内存来创建新数组，但不要填充任何值，如 1 和 0|
|full, full_like	|Produce an array of the given shape and data type with all values set to the indicated "fill value"; full_like takes another array and produces a filled array of the same shape and data type|
||生成给定形状和数据类型的数组，所有值都设置为指示的“填充值”;full_like 接受另一个数组并生成相同形状和数据类型的填充数组|
|eye, identity	|Create a square N × N identity matrix (1s on the diagonal and 0s elsewhere)|
||创建一个平方 N × N 单位矩阵（对角线上为 1，其他地方为 0）|

## Data Types for ndarrays

In [25]:
arr1 = np.array([1,2,3],dtype = np.float64)
arr1

array([1., 2., 3.])

In [26]:
arr2 = np.array([1,2,3],dtype = np.int32)
arr2

array([1, 2, 3], dtype=int32)

In [29]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [31]:
#astype: convert or cast an array from one data type to another
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

In [32]:
float_arr.dtype

dtype('float64')

In [33]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [34]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [38]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.bytes_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [41]:
#使用另一个array的dtype
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [43]:
zeros_uint32 = np.zeros(8, dtype="u4")
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

## NumPy data types

|Type	|Type code	|Description|
|---|---|---|
|int8, uint8	|i1, u1	|Signed and unsigned 8-bit (1 byte) integer types|
|||有符号和无符号 8 位（1 字节）整数类型|
|int16, uint16	|i2, u2	|Signed and unsigned 16-bit integer types|
|||有符号和无符号 16 位整数类型|
|int32, uint32	|i4, u4	|Signed and unsigned 32-bit integer types|
|||有符号和无符号 32 位整数类型|
|int64, uint64	|i8, u8	|Signed and unsigned 64-bit integer types|
|||有符号和无符号 64 位整数类型|
|float16	|f2	|Half-precision floating point|
|||半精度浮点|
|float32	|f4 or f	|Standard single-precision floating point; compatible with C float|
|||标准单精度浮点;兼容 C float|
|float64	|f8 or d	|Standard double-precision floating point; compatible with C double and Python float object|
|||标准双精度浮点;兼容 C double 和 Python float 对象|
|float128	|f16 or g	|Extended-precision floating point|
|||扩展精度浮点|
|complex64, complex128, complex256	|c8, c16, c32	|Complex numbers represented by two 32, 64, or 128 floats, respectively|
|||复数分别由两个 32、64 或 128 个浮点数表示|
|bool	|?	|Boolean type storing True and False values|
|||存储 True 和 False 值的 Boolean 类型|
|object	|O	|Python object type; a value can be any Python object|
|||Python 对象类型;值可以是任何 Python 对象|
|string_	|S	|Fixed-length ASCII string type (1 byte per character); for example, to create a string data type with length 10, use 'S10'|
|||固定长度的 ASCII 字符串类型（每个字符 1 个字节）;例如，若要创建长度为 10 的字符串数据类型，请使用“S10”|
|unicode_	|U	|Fixed-length Unicode type (number of bytes platform specific); same specification semantics as string_ (e.g., 'U10')|
|||固定长度的Unicode类型（特定于平台的字节数）;与 string_ 相同的规范语义（例如，“U10”|

In [ ]:
!git add .
!git command -m '11.40AM'
!git pus